### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by manyhelp** [lijinma/wechat_spider#41]
`C:\WINDOWS\system32> npm install --global --production windows-build-tools

> windows-build-tools@5.2.2 postinstall D:\dev_soft\nodejs\node_modules\node_global\node_modules\windows-build-tools
> node ./dist/index.js

Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\12121\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Python 2.7.16 is already installed, not installing again.

Now configuring the Visual Studio Build Tools..

All done!

+ windows-build-tools@5.2.2
added 145 packages from 99 contributors in 49.194s

PS C:\WINDOWS\system32> npm install wechat_spider -g
D:\dev_soft\nodejs\node_modules\node_global\wechat_spider -> D:\dev_soft\nodejs\node_modules\node_global\node_modules\wechat_spider\bin\wechat_spider

> iconv@2.3.4 install D:\dev_soft\nodejs\node_modules\node_global\node_modules\wechat_spider\node_modules\iconv
> node-gyp rebuild

D:\dev_soft\nodejs\node_modules\node_global\node_modules\wechat_spider\node_modules\iconv>if not defined npm_config_node_gyp (node "D:\dev_soft\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\dev_soft\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn D:\dev_soft\vs2019\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:407:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "D:\\dev_soft\\nodejs\\node.exe" "D:\\dev_soft\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\dev_soft\nodejs\node_modules\node_global\node_modules\wechat_spider\node_modules\iconv
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! iconv@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the iconv@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\dev_soft\nodejs\node_modules\node_cache\_logs\2019-08-01T10_30_47_055Z-debug.log
PS C:\WINDOWS\system32>
`

**Comment by lijinma** [comment]
老铁，抱歉，停止更新了。
